import Link from 'next/link';
import { AppShell } from '@/components/app-shell';
import { workspaceContext } from '@/lib/workspace';
import { query } from '@/lib/db';
import { changeMemberRole, createLabel, deleteWorkspace, inviteMember, removeMember, updateWorkspace } from '@/app/actions';
import { Copy, Shield, Tag, Trash2, UserPlus } from 'lucide-react';
export default async function SettingsPage({params,searchParams}:{params:Promise<{workspaceId:string}>;searchParams:Promise<{invite?:string}>}) {
  const {workspaceId} = await params, {invite} = await searchParams; const {user,role,workspaces,workspace} = await workspaceContext(workspaceId);
  const members = await query<{id:string;name:string;email:string;role:string}>(`SELECT u.id,u.name,u.email,wm.role FROM workspace_members wm JOIN users u ON u.id=wm.user_id WHERE wm.workspace_id=$1 ORDER BY CASE wm.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END,u.name`,[workspaceId]);
  const labels = await query<{id:string;name:string;color:string}>('SELECT id,name,color FROM labels WHERE workspace_id=$1 ORDER BY name',[workspaceId]);
  return <AppShell user={user} workspaces={workspaces} activeWorkspace={workspaceId}><div className="page-header"><div className="eyebrow">SETTINGS</div><h1>Workspace settings</h1><p>Manage your space, people, and labels.</p></div><div className="settings-grid"><div className="settings-main"><section className="panel settings-panel"><div className="panel-title"><Shield size={19}/><div><h2>General</h2><p>Workspace details and defaults</p></div></div><form action={updateWorkspace} className="field-grid"><input type="hidden" name="workspaceId" value={workspaceId}/><label>Workspace name<input name="name" defaultValue={workspace.name} required disabled={!['owner','admin'].includes(role)}/></label><label>Icon<input name="icon" defaultValue={workspace.icon} maxLength={8} disabled={!['owner','admin'].includes(role)}/></label><label>Color<input name="color" type="color" defaultValue={workspace.color} disabled={!['owner','admin'].includes(role)}/></label><label>Default view<select name="defaultView" defaultValue={workspace.default_view} disabled={!['owner','admin'].includes(role)}><option value="board">Board</option><option value="list">List</option></select></label>{['owner','admin'].includes(role)&&<button className="button primary">Save changes</button>}</form></section>
  <section className="panel settings-panel"><div className="panel-title"><UserPlus size={19}/><div><h2>Members</h2><p>{members.length} people in this workspace</p></div></div>{invite&&<div className="invite-link"><strong>Invitation link ready</strong><p>Share this link with the invited person. It expires in 7 days.</p><code>{`${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/invite/${invite}`}</code><Copy size={16}/></div>}{['owner','admin'].includes(role)&&<form action={inviteMember} className="invite-form"><input type="hidden" name="workspaceId" value={workspaceId}/><input name="email" type="email" placeholder="teammate@example.com" required/><select name="role"><option value="member">Member</option><option value="admin">Admin</option><option value="viewer">Viewer</option></select><button className="button primary">Invite</button></form>}<div className="member-list">{members.map(m=><div className="member-row" key={m.id}><span className="avatar">{m.name[0]?.toUpperCase()}</span><span className="member-info"><strong>{m.name}</strong><small>{m.email}</small></span>{role==='owner'&&m.role!=='owner'?<form action={changeMemberRole}><input type="hidden" name="workspaceId" value={workspaceId}/><input type="hidden" name="userId" value={m.id}/><select name="role" defaultValue={m.role} aria-label={`Role for ${m.name}`}><option value="admin">Admin</option><option value="member">Member</option><option value="viewer">Viewer</option></select><button className="text-button">Save</button></form>:<span className="role-pill">{m.role}</span>}{['owner','admin'].includes(role)&&m.role!=='owner'&&m.id!==user.id&&<form action={removeMember}><input type="hidden" name="workspaceId" value={workspaceId}/><input type="hidden" name="userId" value={m.id}/><button className="danger-icon" title={`Remove ${m.name}`}><Trash2 size={16}/></button></form>}</div>)}</div></section>
  <section className="panel settings-panel"><div className="panel-title"><Tag size={19}/><div><h2>Labels</h2><p>Organize tasks with color-coded tags</p></div></div><div className="label-list">{labels.map(l=><span className="label-chip" key={l.id} style={{background:`${l.color}20`,color:l.color}}><i style={{background:l.color}}/>{l.name}</span>)}</div>{role!=='viewer'&&<form action={createLabel} className="invite-form"><input type="hidden" name="workspaceId" value={workspaceId}/><input name="name" placeholder="Label name" required maxLength={40}/><input type="color" name="color" defaultValue="#6d5efc" className="color-input"/><button className="button secondary">Add label</button></form>}</section>
  {role==='owner'&&<section className="panel settings-panel danger-zone"><h2>Danger zone</h2><p>Deleting a workspace permanently removes its projects and tasks.</p><form action={deleteWorkspace}><input type="hidden" name="workspaceId" value={workspaceId}/><button className="button danger"><Trash2 size={16}/> Delete workspace</button></form></section>}</div><aside className="settings-aside"><h3>Roles at a glance</h3><p><strong>Owner</strong> controls everything, including deletion.</p><p><strong>Admin</strong> manages members and projects.</p><p><strong>Member</strong> works on assigned projects.</p><p><strong>Viewer</strong> can see work without editing.</p><Link href={`/w/${workspaceId}`} className="text-button">← Back to workspace</Link></aside></div></AppShell>;
}
