import { DesktopObject } from '@/components/desktop-object';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { projectContext } from '@/lib/project';
import { query } from '@/lib/db';
import { updateTask, addSubtask, toggleSubtask, addComment, toggleTaskLabel } from '@/app/actions';

export default async function TaskPage({params}:{params:Promise<{workspaceId:string;projectId:string;taskId:string}>}) {
  const {workspaceId,projectId,taskId} = await params;
  const {user,workspaces,project,canEdit} = await projectContext(workspaceId,projectId);
  const [task] = await query<{id:string;title:string;description:string;status:string;priority:string;assignee_id:string|null;due_date:string|null}>(
    `SELECT id,title,description,status,priority,assignee_id,to_char(due_date,'YYYY-MM-DD') AS due_date FROM tasks WHERE id=$1 AND project_id=$2`,[taskId,projectId]);
  if (!task) notFound();
  const [people,subtasks,comments,labels,activity] = await Promise.all([
    query<{id:string;name:string}>('SELECT u.id,u.name FROM users u JOIN workspace_members wm ON wm.user_id=u.id WHERE wm.workspace_id=$1 ORDER BY u.name',[workspaceId]),
    query<{id:string;title:string;is_complete:boolean}>('SELECT id,title,is_complete FROM subtasks WHERE task_id=$1 ORDER BY created_at',[taskId]),
    query<{id:string;name:string;text:string;created_at:Date}>('SELECT c.id,u.name,c.text,c.created_at FROM comments c JOIN users u ON u.id=c.user_id WHERE c.task_id=$1 ORDER BY c.created_at',[taskId]),
    query<{id:string;name:string;color:string;selected:boolean}>('SELECT l.id,l.name,l.color,EXISTS(SELECT 1 FROM task_labels tl WHERE tl.label_id=l.id AND tl.task_id=$2) AS selected FROM labels l WHERE l.workspace_id=$1 ORDER BY l.name',[workspaceId,taskId]),
    query<{id:string;name:string;details:string;created_at:Date}>('SELECT a.id,u.name,a.details,a.created_at FROM activity_logs a JOIN users u ON u.id=a.user_id WHERE a.task_id=$1 ORDER BY a.created_at DESC LIMIT 30',[taskId]),
  ]);
  return <AppShell user={user} workspaces={workspaces} activeWorkspace={workspaceId}><Link className="back-link" href={`/w/${workspaceId}/p/${projectId}`}>← Back to {project.name}</Link><div className="page-header"><div className="eyebrow">TASK DETAILS</div><h1>{task.title}</h1></div><div className="task-detail-grid"><div>
    <section className="panel task-form-panel"><form action={updateTask} className="task-edit-form"><input type="hidden" name="taskId" value={taskId}/><fieldset disabled={!canEdit} className="action-fields"><label>Title<input name="title" defaultValue={task.title} required maxLength={200}/></label><label>Description<textarea name="description" defaultValue={task.description} rows={5} maxLength={10000}/></label><div className="field-grid"><label>Status<select name="status" defaultValue={task.status}>{['todo','in_progress','review','done'].map(s=><option value={s} key={s}>{s.replaceAll('_',' ')}</option>)}</select></label><label>Priority<select name="priority" defaultValue={task.priority}>{['low','medium','high','urgent'].map(p=><option key={p}>{p}</option>)}</select></label><label>Assignee<select name="assigneeId" defaultValue={task.assignee_id || ''}><option value="">Unassigned</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Due date<input type="date" name="dueDate" defaultValue={task.due_date || ''}/></label></div>{canEdit&&<button className="button primary"><DesktopObject kind="disk"/><span className="desktop-caption">Save changes</span></button>}</fieldset></form></section>
    <section className="panel task-section"><h2>Checklist</h2><div className="checklist">{subtasks.map(s=><form action={toggleSubtask} key={s.id} className="check-row"><input type="hidden" name="taskId" value={taskId}/><input type="hidden" name="subtaskId" value={s.id}/><button className={`check-box ${s.is_complete?'checked':''}`} disabled={!canEdit} aria-label={`${s.is_complete?'Uncheck':'Complete'} ${s.title}`} aria-pressed={s.is_complete}>{s.is_complete?'✓':''}</button><span className={s.is_complete?'completed':''}>{s.title}</span></form>)}</div>{canEdit&&<form action={addSubtask} className="add-inline"><input type="hidden" name="taskId" value={taskId}/><input name="title" aria-label="Checklist item" placeholder="Add a checklist item" required maxLength={200}/><button className="button primary"><DesktopObject kind="document"/><span className="desktop-caption">Add</span></button></form>}</section>
    <section className="panel task-section"><h2>Comments</h2>{comments.map(c=><div className="comment" key={c.id}><span className="avatar">{c.name[0]}</span><div><div className="comment-meta"><strong>{c.name}</strong><time>{c.created_at.toLocaleDateString('en-GB')}</time></div><p>{c.text}</p></div></div>)}{!comments.length&&<p className="muted">Start the conversation.</p>}{canEdit&&<form action={addComment} className="comment-form"><input type="hidden" name="taskId" value={taskId}/><textarea name="text" aria-label="Comment" placeholder="Write a comment…" required maxLength={5000} rows={3}/><button className="button primary"><DesktopObject kind="mail"/><span className="desktop-caption">Post comment</span></button></form>}</section>
    </div><aside><section className="panel task-side-panel"><h2>Labels</h2><div className="label-list">{labels.map(l=><form action={toggleTaskLabel} key={l.id}><input type="hidden" name="taskId" value={taskId}/><input type="hidden" name="labelId" value={l.id}/><input type="hidden" name="mode" value={l.selected?'remove':'add'}/><button className={`label-option ${l.selected?'selected':''}`} disabled={!canEdit} aria-pressed={l.selected}><i style={{background:l.color}}/>{l.name}</button></form>)}</div>{!labels.length&&<p className="muted">Add labels in workspace settings.</p>}</section><section className="panel task-side-panel"><h2>Activity</h2><div className="timeline">{activity.map(a=><div className="timeline-item" key={a.id}><span className="timeline-dot"/><strong>{a.name}</strong><p>{a.details}</p><time>{a.created_at.toLocaleDateString('en-GB')}</time></div>)}</div></section></aside></div></AppShell>;
}
