import Link from 'next/link';
import { Bell, Blocks, ChevronDown, LayoutDashboard, LogOut, Plus, Settings } from 'lucide-react';
import type { User } from '@/lib/auth';
import { query } from '@/lib/db';
import { signOut, markNotificationRead } from '@/app/actions';

type Workspace = {id:string;name:string;icon:string;color:string;role:string};
export async function AppShell({user,workspaces,activeWorkspace,children}: {user:User;workspaces:Workspace[];activeWorkspace?:string;children:React.ReactNode}) {
  const projects = activeWorkspace ? await query<{id:string;name:string;color:string}>("SELECT id,name,color FROM projects WHERE workspace_id=$1 AND status='active' ORDER BY created_at DESC",[activeWorkspace]) : [];
  const notifications = await query<{id:string;message:string;task_id:string|null;created_at:Date;is_read:boolean;project_id:string|null;workspace_id:string|null}>(`SELECT n.id,n.message,n.task_id,n.created_at,n.is_read,t.project_id,p.workspace_id FROM notifications n LEFT JOIN tasks t ON t.id=n.task_id LEFT JOIN projects p ON p.id=t.project_id WHERE n.user_id=$1 ORDER BY n.created_at DESC LIMIT 8`,[user.id]);
  return <div className="app-layout"><aside className="sidebar"><Link className="brand" href="/"><span className="brand-mark"><Blocks size={22}/></span><span>workspace<span className="brand-light">manager</span></span></Link>
    <div className="side-label">WORKSPACE</div><nav className="side-nav"><Link href="/" className={!activeWorkspace?'side-link active':'side-link'}><LayoutDashboard size={18}/> Overview</Link>
      {workspaces.map(w=><Link key={w.id} href={`/w/${w.id}`} className={activeWorkspace===w.id?'side-link active':'side-link'}><span className="side-dot" style={{background:w.color}}/>{w.name}</Link>)}
    </nav><div className="side-label side-label-spaced">PROJECTS</div><nav className="side-nav">{projects.map(p=><Link className="side-link project-link" href={`/w/${activeWorkspace}/p/${p.id}`} key={p.id}><span className="project-dot" style={{background:p.color}}/>{p.name}</Link>)}{activeWorkspace && <Link href={`/w/${activeWorkspace}`} className="side-link muted-link"><Plus size={17}/> New project</Link>}</nav>
    <div className="sidebar-bottom">{activeWorkspace && <Link href={`/w/${activeWorkspace}/settings`} className="side-link"><Settings size={18}/> Settings & members</Link>}<div className="sidebar-user"><span className="avatar">{user.name[0]?.toUpperCase()}</span><span><strong>{user.name}</strong><small>{user.email}</small></span><form action={signOut}><button title="Sign out" className="logout"><LogOut size={17}/></button></form></div></div></aside>
    <main className="main-content"><header className="topbar"><div className="breadcrumb"><Link href="/">Workspace</Link>{activeWorkspace && <><span>/</span><strong>{workspaces.find(w=>w.id===activeWorkspace)?.name}</strong></>}</div><div className="top-actions"><details className="notification-menu"><summary title="Notifications"><Bell size={19}/>{notifications.some(n=>!n.is_read)&&<i/>}</summary><div className="notification-popover"><h3>Notifications</h3>{notifications.length ? notifications.map(n=><div className={n.is_read?'notification':'notification unread'} key={n.id}><span>{n.message}</span>{n.task_id && <Link href={`/w/${n.workspace_id}/p/${n.project_id}/t/${n.task_id}`}>View task</Link>}{!n.is_read && <form action={markNotificationRead}><input type="hidden" name="notificationId" value={n.id}/><button>Mark read</button></form>}</div>) : <p className="muted">You&apos;re all caught up.</p>}</div></details><span className="top-avatar">{user.name[0]?.toUpperCase()}</span><ChevronDown size={14} className="muted"/></div></header><div className="content-wrap">{children}</div></main></div>;
}
